services:
  php: 
    build: './docker/php'
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PHP_PORT:-8091}:80
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:80 -t .

  db:
      image: mysql:8.0
      ports:
      - ${DB_PORT:-3307}:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
        MYSQL_DATABASE: ${DB_DATABASE:-racoin}
        MYSQL_USER: ${DB_USER:-user}
        MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-8083}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

volumes:
    dbdata: